import type { PlayerGender } from './entities/PlayerModel';
import type { HandTool } from './entities/Player';
import type { BaitBarrelInfo } from './systems/BaitBarrelSystem';
import type { BrewBarrelInfo } from './systems/BrewBarrelSystem';
import type { CampfireInfo } from './systems/CampfireSystem';
import type { CookingStationInfo } from './systems/CookingStationSystem';
import type { CraftId, Tools } from './systems/Crafting';
import type { DropInfo } from './systems/DropSystem';
import type { EquipKind, EquipSlot } from './systems/Equipment';
import type { FishingState } from './systems/FishingSystem';
import type { FacilityKind } from './systems/Facilities';
import type { HudBuff } from './systems/BuffSystem';
import type { InventorySlot, ResourceKind } from './systems/Inventory';
import type { LoomInfo } from './systems/LoomSystem';
import type { SmelterInfo } from './systems/SmelterSystem';

/** 游戏层与 React、网络层共享的只读 HUD 契约。 */
export type HudSnapshot = {
  hunger: number;
  thirst: number;
  health: number;
  dead: boolean;
  arrow: number;
  bait: number;
  heldFenceCount: number;
  heldPlaceCount: number;
  heldItemKind: FacilityKind | null;
  placeables: { kind: ResourceKind; count: number }[];
  slots: InventorySlot[];
  capacity: number;
  hasAxe: boolean;
  hasPickaxe: boolean;
  hasShovel: boolean;
  hasHoe: boolean;
  hasFishingrod: boolean;
  hasBow: boolean;
  hasSword: boolean;
  hasLasso: boolean;
  lassoCount: number;
  leading: boolean;
  nearTether: boolean;
  toolTiers: Tools;
  craftedIds: CraftId[];
  nearCrate: boolean;
  nearBaitBarrel: boolean;
  nearBrewBarrel: boolean;
  nearSmelter: boolean;
  nearLoom: boolean;
  nearBed: boolean;
  bedSleeping: boolean;
  bedSleepProgress: number;
  crateSlots: InventorySlot[] | null;
  crateCapacity: number | null;
  baitBarrelInfo: BaitBarrelInfo | null;
  brewBarrelInfo: BrewBarrelInfo | null;
  smelterInfo: SmelterInfo | null;
  nearCookingStation: boolean;
  cookingStationInfo: CookingStationInfo | null;
  loomInfo: LoomInfo | null;
  equipped: Record<EquipSlot, EquipKind | null>;
  gender: PlayerGender;
  tool: HandTool;
  craftId: CraftId | null;
  craftProgress: number;
  workbenchCrafted: boolean;
  campfirePlaced: boolean;
  workbenchProgress: number;
  workbenchLevel: number;
  nearWorkbench: boolean;
  campfireProgress: number;
  nearCampfire: boolean;
  campfireInfo: CampfireInfo | null;
  eatName: string | null;
  eatProgress: number;
  autoEquipProgress: number;
  respawnLeft: number | null;
  poseidonGrace: boolean;
  canFish: boolean;
  fishingState: FishingState | null;
  fishingProgress: number;
  fishingTier: number;
  fishingWaitLeft: number | null;
  biteActive: boolean;
  biteClicks: number;
  biteNeed: number;
  treasureKind: ResourceKind | null;
  collectTreasure: ResourceKind | null;
  nearDrop: DropInfo | null;
  notice: { id: number; text: string } | null;
  day: number;
  busy: boolean;
  moving: boolean;
  indicator: { label: string | null; progress: number | null; color?: string };
  buffs: HudBuff[];
};

export type VitalLevels = Pick<HudSnapshot, 'hunger' | 'thirst' | 'health'>;

export type PickupToast = {
  items: { kind: ResourceKind; count: number }[];
  x: number;
  y: number;
};

export type MapSnapshot = {
  island: { width: number; length: number };
  terrain: { columns: number; rows: number; pixels: Uint8Array };
  localPlayerId: string;
  players: { id: string; name: string; x: number; z: number; dead: boolean }[];
  workbenches: { x: number; z: number }[];
};
