import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const webpackModule=require('next/dist/compiled/webpack/webpack');webpackModule.init();
const directory=path.resolve('dist/cola-preview');fs.mkdirSync(directory,{recursive:true});
fs.writeFileSync(path.join(directory,'loader.cjs'),`const ts=require(${JSON.stringify(require.resolve('typescript'))});module.exports=function(source){return ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText;};`);
await new Promise<void>((resolve,reject)=>webpackModule.webpack({mode:'production',optimization:{minimize:false},entry:path.resolve('scripts/cola-preview/page.ts'),output:{path:directory,filename:'bundle.js'},resolve:{extensions:['.ts','.tsx','.js'],alias:{'react-dom/server$':require.resolve('react-dom/server.browser')}},module:{rules:[{test:/\.tsx?$/,use:path.join(directory,'loader.cjs')}]},performance:{hints:false}},(error:Error|null,stats:{hasErrors():boolean;toString():string})=>{if(error||stats.hasErrors())reject(error??new Error(stats.toString()));else resolve();}));
const css=`*{box-sizing:border-box}body{margin:0;background:#f7f4eb;color:#343c35;font:15px/1.6 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:32px 22px}small,.hint{color:#758071}header small{letter-spacing:3px}h1{font-size:clamp(25px,4vw,38px);margin:8px 0}h2{font-size:19px}header p{max-width:700px}.layout{display:grid;grid-template-columns:1.5fr 1fr;gap:26px;margin-top:28px}#stage{height:440px;border-radius:24px;overflow:hidden}canvas{display:block;touch-action:none}.zoom-controls{margin-top:14px;padding:14px;background:#eeede3;border-radius:14px}.zoom-controls>label{display:flex;justify-content:space-between;align-items:center}.zoom-controls output{font-weight:700;font-variant-numeric:tabular-nums}.zoom-controls input{display:block;width:100%;height:44px;margin:0;accent-color:#738768;cursor:pointer}.zoom-controls .controls{margin-top:0}.zoom-controls .hint{margin:8px 0 0;font-size:12px}.controls{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}button,select{font:inherit;min-height:44px;border:1px solid #d4d9c9;background:#fffdf7;border-radius:12px;padding:8px 13px;color:inherit;cursor:pointer}button[aria-pressed=true]{background:#e2ead7;border-color:#738768;box-shadow:inset 0 0 0 1px #738768}button:focus-visible{outline:3px solid #a97d44;outline-offset:3px}.icon-choice{display:flex;width:100%;gap:15px;text-align:left;margin-bottom:12px;align-items:center;padding:14px}.big{width:85px;flex-shrink:0}.icon-choice small{display:block;font-size:12px;margin-top:4px}.sizes{display:flex;align-items:center;gap:12px;margin-top:8px}.sizes span:nth-child(1){width:24px}.sizes span:nth-child(2){width:36px}.sizes span:nth-child(3){width:48px}svg{display:block;width:100%;height:auto}.reference{padding:14px;border-top:1px solid #d7dccc;color:#758071}.reference div{display:flex;gap:20px;margin-top:12px}.reference svg{width:52px}.reference p{font-size:12px}footer{margin-top:28px;padding:22px;background:#eeede3;border-radius:18px}textarea{display:block;width:100%;min-height:76px;padding:12px;border:1px solid #d2d7c6;border-radius:10px;font:inherit;background:#fffdf7;margin-bottom:12px}@media(max-width:700px){main{padding:24px 14px}.layout{grid-template-columns:1fr}#stage{height:370px}.icon-choice{min-height:120px}}`;
const eggCss=`.egg-selection{margin-top:28px}.egg-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px}.egg-grid article{padding:16px;background:#eeede3;border-radius:18px}.egg-grid h3{margin:0}.egg-grid p{font-size:13px;color:#758071}.egg-scene{background:#7eac9a;border-radius:14px;overflow:hidden}.egg-closeup{width:160px;margin:12px auto;background:#7eac9a;border-radius:12px;overflow:hidden}`;
const bundle=fs.readFileSync(path.join(directory,'bundle.js'),'utf8').replace(/<\/script/gi,'<\\/script');
fs.writeFileSync(path.join(directory,'index.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>可乐 · 临时选型</title><style>${css}${eggCss}</style><body><script>${bundle}</script></body></html>`);
console.log('临时选型页面已生成：dist/cola-preview/index.html');

