/** 研究仅接受生鲜食材与面粉；奶种和鱼种分别匹配。 */
export const RESEARCH_INGREDIENT_NAMES = {
  flour: '面粉',
  berry: '浆果',
  fruitFruit: '苹果',
  milk: '羊奶',
  cowMilk: '牛奶',
  carrot: '胡萝卜',
  potato: '土豆',
  sweetPotato: '红薯',
  corn: '玉米',
  soybean: '大豆',
  tomato: '番茄',
  pepper: '辣椒',
  eggplant: '茄子',
  strawberry: '草莓',
  cabbage: '卷心菜',
  pumpkin: '南瓜',
  gameMeat: '兽肉',
  birdMeat: '鸟肉',
  crabMeat: '蟹肉',
  sardine: '沙丁鱼',
  shrimp: '虾',
  perch: '鲈鱼',
  loach: '泥鳅',
  puffer: '河豚',
  cuttlefish: '墨鱼',
  anchovy: '鳀鱼',
  horseMackerel: '竹荚鱼',
  yellowCroaker: '小黄鱼',
  saury: '秋刀鱼',
  hairtail: '带鱼',
  grouper: '石斑鱼',
  catfish: '巨鲶',
  grassCarp: '草鱼',
  swordfish: '剑鱼',
  manta: '魔鬼鱼',
  goldenFish: '黄金鱼',
  oakFruit: '橡果',
  pineFruit: '松果',
} as const;

export type ResearchIngredient = keyof typeof RESEARCH_INGREDIENT_NAMES;
export const RESEARCH_INGREDIENTS = Object.keys(RESEARCH_INGREDIENT_NAMES) as ResearchIngredient[];
