import type { HandTool } from '../entities/Player';
import type { PlayerGender } from '../entities/PlayerModel';
import type { AnimalSpecies } from '../entities/Wildlife';
import type { CraftId, ToolId } from '../systems/Crafting';
import type { EquipSlot } from '../systems/Equipment';
import type { GmConfig } from '../systems/GmSystem';
import type { ResourceKind } from '../systems/Inventory';

/** 客人上行的动作名与参数元组；保持现有线格式，仅为发送端和注册表提供静态约束。 */
export interface NetActionArgs {
  tool: [tool: HandTool, placeKind: ResourceKind | null];
  eatFood: [kind?: ResourceKind];
  eatUntilFull: [kind?: ResourceKind];
  startFishing: [];
  hookFish: [];
  claimTreasure: [];
  sleep: [];
  useFacility: [kind: ResourceKind];
  baitBarrelFeed: [kind: ResourceKind, count: number];
  baitBarrelCollect: [];
  baitBarrelTakeFoods: [];
  brewBarrelFeed: [kind: ResourceKind, count: number];
  brewBarrelCollect: [];
  brewBarrelTakeRaw: [];
  smelterFeed: [count: number];
  smelterCollect: [];
  smelterTakeOre: [];
  cookingAddFuel: [kind: ResourceKind];
  cookingRoast: [kind: ResourceKind, count: number];
  cookingBoil: [kind: ResourceKind, count: number];
  cookingCollect: [];
  cookingTakeBoil: [];
  loomFeed: [count: number];
  loomCollect: [];
  loomTakeRope: [];
  useSeed: [kind: ResourceKind];
  useBottle: [];
  pickupDrop: [];
  crateStore: [kind: ResourceKind, count: number | null];
  crateTake: [kind: ResourceKind, count: number | null];
  campfireAddFuel: [kind: ResourceKind];
  campfireCook: [kind: ResourceKind, count: number];
  dropItem: [kind: ResourceKind, count: number];
  moveItem: [from: number, to: number];
  sortInventory: [];
  equipItem: [kind: ResourceKind];
  unequipItem: [slot: EquipSlot];
  craftTool: [id: CraftId];
  craftAtWorkbench: [id: CraftId, count: number];
  upgradeWorkbench: [];
  arrowHit: [kind: 'wildlife' | 'crab' | 'bird', animalId: number, x: number, z: number];
  arrowShot: [dx: number, dz: number];
  swordHit: [animalId: number];
  lassoThrow: [dx: number, dz: number];
  lassoHit: [animalId: number, x: number, z: number];
  lassoStake: [];
  lassoUntie: [];
  milkSheep: [sheepId: number, x: number, z: number];
  gmSpawnAnimal: [species: AnimalSpecies];
  gmTriggerCrocodile: [];
  gmGiveItem: [kind: ResourceKind, count: number];
  gmGiveTool: [tool: ToolId, tier: 1 | 2 | 3];
  gmSetGender: [gender: PlayerGender];
  gmRestoreStatus: [];
  gmSetTime: [time: number];
  gmSetDay: [day: number];
  gmSetWeather: [weather: 'sunny' | 'rain'];
  gmConfig: [config: GmConfig];
}

export type NetActionName = keyof NetActionArgs;
